---
- name: Ensure network benchmark validation variables are set with defaults
  set_fact:
    validation: >-
      {{
        validation | default({}) | combine({
          'run_network_benchmark': validation.run_network_benchmark | default(true)
        }, recursive=True)
      }}

- name: Set role default variables
  set_fact:
    _iperf_port: "{{ validation.network_benchmark.iperf_port | d(5201) }}"
    _iperf_test_time: "{{ validation.network_benchmark.iperf_test_time | d(10) }}"
    _iperf_started_by_us: false

- name: Run network benchmarking
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/network_benchmark.yml"
  when: validation.run_network_benchmark

